# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/master/src/schemas/json/dependabot-2.0.json
version: 2
updates:
  - package-ecosystem: docker
    cooldown:
      default-days: 7
    commit-message:
      prefix: "chore"
    directory: /
    schedule:
      interval: weekly
    target-branch: dev
  - package-ecosystem: github-actions
    cooldown:
      default-days: 7
    commit-message:
      prefix: "chore"
    directory: /
    schedule:
      interval: weekly
    target-branch: dev
  - package-ecosystem: npm
    cooldown:
      default-days: 7
    commit-message:
      prefix: "chore"
    directory: "/"
    schedule:
      interval: weekly
    target-branch: dev
  - package-ecosystem: "uv"
    cooldown:
      default-days: 7
      semver-major-days: 14
    commit-message:
      prefix: "chore"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: dev
